version: 4.0.{build}
branches:
  only:
  - develop
image: Visual Studio 2019
build:
  project: nUpdate.sln
  verbosity: minimal
deploy:
- provider: FTP
  host: trade-programming.de
  protocol: ftps
  username: ftp1@trade-programming.de
  password:
    secure: F1iZciMuQW3MCkaP6s6yM0z0PqoZe5FGynQiKt+TzYs=
  folder: /nupdate.net/htdocs/build
  on:
    branch: develop
notifications:
- provider: Email
  to:
  - dominic.beger@hotmail.de
  subject: AppVeyor Build Succeeded
  message: The newest build of the develop-branch was successfully created.
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
- provider: Email
  to:
  - dominic.beger@hotmail.de
  subject: AppVeyor Build Failed
  message: The newest build of the develop-branch was successfully failed.
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false